import Head from "next/head";
import Link from "next/link";
import FeatureSection from "../components/landingPage/featureSection";
import FAQ from "../components/landingPage/faq";

const Home: React.FC = () => {
	return (
		<>
			<Head>
				<title>FosterCollab Home</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<section
					className="pt-24 md:mt-0 md:h-screen flex flex-col justify-center text-center md:text-left md:flex-row md:justify-between md:items-center lg:px-48 md:px-12 px-4 bg-secondary">
					<div className="md:flex-1 md:mr-10">
						<h1 className="font-pt-serif text-5xl font-bold mb-7">
        A headline for your
							<span className="bg-underline1 bg-left-bottom bg-no-repeat pb-2 bg-100%">
          cool website
							</span>
						</h1>
						<p className="font-pt-serif font-normal mb-7">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum harum
        tempore consectetur voluptas, cumque nobis laboriosam voluptatem.
						</p>
						<div className="font-montserrat">
							<button className="bg-black px-6 py-4 rounded-lg border-2 border-black border-solid text-white mr-2 mb-2">
          Call to action
							</button>
							<button className="px-6 py-4 border-2 border-black border-solid rounded-lg">
          Secondary action
							</button>
						</div>
					</div>
					<div className="flex justify-around md:block mt-8 md:mt-0 md:flex-1">
						<div className="relative">
							<img src='/assets/Highlight1.svg' alt="" className="absolute -top-16 -left-10" />
						</div>
						<img src='/assets/MacBook Pro.png' alt="Macbook" />
						<div className="relative">
							<img src='/assets/Highlight2.svg' alt="" className="absolute -bottom-10 -right-6" />
						</div>
					</div>
				</section>

				<section className="bg-black text-white sectionSize">
					<div>
						<h2 className="secondaryTitle bg-underline2 bg-100%">How it works</h2>
					</div>
					<div className="flex flex-col md:flex-row">
						<div className="flex-1 mx-8 flex flex-col items-center my-4">
							<div className="border-2 rounded-full bg-secondary text-black h-12 w-12 flex justify-center items-center mb-3">
          1
							</div>
							<h3 className="font-montserrat font-medium text-xl mb-2">Eat</h3>
							<p className="text-center font-montserrat">
          Lorem ipsum dolor, sit amet consectetur adipisicing elit.
							</p>
						</div>
						<div className="flex-1 mx-8 flex flex-col items-center my-4">
							<div className="border-2 rounded-full bg-secondary text-black h-12 w-12 flex justify-center items-center mb-3">
          2
							</div>
							<h3 className="font-montserrat font-medium text-xl mb-2">Sleep</h3>
							<p className="text-center font-montserrat">
          Lorem ipsum dolor, sit amet consectetur adipisicing elit.
							</p>
						</div>
						<div className="flex-1 mx-8 flex flex-col items-center my-4">
							<div className="border-2 rounded-full bg-secondary text-black h-12 w-12 flex justify-center items-center mb-3">
          3
							</div>
							<h3 className="font-montserrat font-medium text-xl mb-2">Rave</h3>
							<p className="text-center font-montserrat">
          Lorem ipsum dolor, sit amet consectetur adipisicing elit.
							</p>
						</div>
					</div>
				</section>

				<FeatureSection />

				<section className="sectionSize bg-secondary py-0">
					<div>
						<h2 className="secondaryTitle bg-underline4 mb-0 bg-100%">Pricing</h2>
					</div>
					<div className="flex w-full flex-col md:flex-row">

						<div className='flex-1 flex flex-col mx-6 shadow-2xl relative bg-secondary rounded-2xl py-5 px-8 my-8 md:top-24'>
							<h3 className="font-pt-serif font-normal text-2xl mb-4">
          The Good
							</h3>
							<div className="font-montserrat font-bold text-2xl mb-4">
          $25
								<span className="font-normal text-base"> / month</span>
							</div>

							<div className="flex">
								<img src='/assets/logos/CheckedBox.svg' alt="" className="mr-1" />
								<p>Benefit #1</p>
							</div>
							<div className="flex">
								<img src='/assets/logos/CheckedBox.svg' alt="" className="mr-1" />
								<p>Benefit #2</p>
							</div>
							<div className="flex">
								<img src='/assets/logos/CheckedBox.svg' alt="" className="mr-1" />
								<p>Benefit #3</p>
							</div>

							<button className=" border-2 border-solid border-black rounded-xl text-lg py-3 mt-4">
          Choose plan
							</button>
						</div>

						<div className='flex-1 flex flex-col mx-6 shadow-2xl relative bg-secondary rounded-2xl py-5 px-8 my-8 md:top-12'>
							<h3 className="font-pt-serif font-normal text-2xl mb-4">
          The Bad
							</h3>
							<div className="font-montserrat font-bold text-2xl mb-4">
          $40
								<span className="font-normal text-base"> / month</span>
							</div>

							<div className="flex">
								<img src='/assets/logos/CheckedBox.svg' alt="" className="mr-1" />
								<p>Benefit #1</p>
							</div>
							<div className="flex">
								<img src='/assets/logos/CheckedBox.svg' alt="" className="mr-1" />
								<p>Benefit #2</p>
							</div>
							<div className="flex">
								<img src='/assets/logos/CheckedBox.svg' alt="" className="mr-1" />
								<p>Benefit #3</p>
							</div>

							<button className=" border-2 border-solid border-black rounded-xl text-lg py-3 mt-4">
          Choose plan
							</button>
						</div>

						<div className='flex-1 flex flex-col mx-6 shadow-2xl relative bg-secondary rounded-2xl py-5 px-8 my-8 md:top-24'>
							<h3 className="font-pt-serif font-normal text-2xl mb-4">
          The Ugly
							</h3>
							<div className="font-montserrat font-bold text-2xl mb-4">
          $50
								<span className="font-normal text-base"> / month</span>
							</div>

							<div className="flex">
								<img src='/assets/logos/CheckedBox.svg' alt="" className="mr-1" />
								<p>Benefit #1</p>
							</div>
							<div className="flex">
								<img src='/assets/logos/CheckedBox.svg' alt="" className="mr-1" />
								<p>Benefit #2</p>
							</div>
							<div className="flex">
								<img src='/assets/logos/CheckedBox.svg' alt="" className="mr-1" />
								<p>Benefit #3</p>
							</div>

							<button className=" border-2 border-solid border-black rounded-xl text-lg py-3 mt-4">
          Choose plan
							</button>
						</div>

					</div>
				</section>
				<FAQ />
			</main>
		</>
	);
}
export default Home